### ISSUE TITLE
myname.github.io website does not work after building and pushing everything to Github

### ISSUE THREAD

**Issue by durraniu** [privefl/rmarkdown-website-template#1]
Hi Florian, thanks for your very thorough instructions for building a Rmd site with github. I followed all your steps after forking your repo. Everything is pushed to my repo `umairdurrani.github.io` but whenever I try to visit this site I get a 404 error. Could you please check my repo to see if I did something wrong? Once again, thank you very much!

**Comment by privefl** [comment]
I think your repo should be `durraniu.github.io`. 
In other words, you have to use your exact GitHub's pseudo for this to work.

**Comment by durraniu** [comment]
Thanks a lot for so quick response. It is working now. :)
